### ISSUE TITLE
Improve UI of website in different forms and Navbar

### ISSUE THREAD

**Issue by luckykumarirai** [Khushi0321/Digital_Hospital#13]
I would like to work on your project and I have some queries regarding some parts of the project. Would you tell me where we discuss all those stuff?

**Comment by jatinjain001** [comment]
I would like to work on it Please assign It to me.

**Comment by gaurav24072002** [comment]
I can also help you to make some great changes to make the User Interface look good . Please assign it to me

**Comment by Sloth-Panda** [comment]
@khusi can I work on this for Dwoc?
