### ISSUE TITLE
View Profile button not working

### ISSUE THREAD

**Issue by gaurav24072002** [Khushi0321/Digital_Hospital#39]
In the appointment.html file both the view profile button of Suresh Desai and Lalita Gupta is not working so we should connect the button to the specified source of profile of docters

**Comment by gaurav24072002** [comment]
I would like to solve this issue please assign it to me...

**Comment by prajjwal1231** [comment]
is this issue adds under DWOC ? if yes then how can i contribute in this project.

**Comment by Sloth-Panda** [comment]
@khusi can i work on this for DWOC. please assign me.
