### ISSUE TITLE
Integrate Welcome and Greeting Bot 

### ISSUE THREAD

**Issue by akrish4** [Khushi0321/Digital_Hospital#6]
Hi @khushi0302001 
I would like to contribute to this amazing project
I can add a config file and integrate the bot so that whenever a new user opens a issue or pr , the bot will comment and greet the user with a proper message

Let me know if you are interested

Kindly do assign me
Kindly do add the DWOC and Level label

**Comment by khushi-saxena** [comment]
Ok sure! You can.

**Comment by akrish4** [comment]
thank you @khushi0302001 
But u added wrong level label
It is not just simply level , it shud  be Level-1, Level-2, Level-3, Level-4 , Level-5
Add any of the above label that you think appropriate

**Comment by khushi-saxena** [comment]
@akrish4 Done!

**Comment by akrish4** [comment]
#9   PR

**Comment by akrish4** [comment]
https://github.com/apps/welcome 
this is the bot , install and configure and i have added the file now after configuring , bot will do rest by itsown 
these bot  are made by github only
